name: Deploy Frontend and Backend

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      # Frontend CI
      - name: Install frontend dependencies
        run: cd frontend && npm install

      - name: Lint frontend
        run: cd frontend && npm run lint

      - name: Format frontend
        run: cd frontend && npm run format

      # Backend CI
      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Lint backend
        run: cd backend && npm run lint

      - name: Format backend
        run: cd backend && npm run format

      # Docker build and push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/phone-link-org/phone-link/frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ghcr.io/phone-link-org/phone-link/backend:latest
